---
- hosts: opentripplanner:geocoder
  user: root

  # Gather facts only


- hosts: graphbuilder
  user: root

  vars:
    osm_url: http://download.geofabrik.de/openstreetmap/europe/netherlands.osm.pbf
    gtfs_url: http://gtfs.ovapi.nl/new/gtfs-nl.zip
    gtfs_url: http://gtfs.ovapi.nl/new/gtfs-.zip
    data_expiry: 86400  # 86300s = 1d

  tasks:

  - name: Create data directory
    file: path=/srv/otp/data state=directory mode=0755

  - name: Download OSM data
    get_url: url={{ osm_url }} dest=/srv/otp/data/osm.pbf force=yes
    when: "/srv/otp/data/osm.pbf"|file_age > data_expiry
    register: osm_download

  - name: Download GTFS data
    get_url: url={{ gtfs_url }} dest=/srv/otp/data/gtfs.zip force=yes
    when: "/srv/otp/data/gtfs.zip"|file_age > data_expiry
    register: gtfs_download

  - name: Download RET GTFS data
    get_url: url={{ gtfs_ret_url }} dest=/srv/otp/data/gtfs_ret.zip force=yes
    when: "/srv/otp/data/gtfs_ret.zip"|file_age > data_expiry
    register: gtfs2_download

  - name: Build graph
    command: java -Xmx20G -jar /usr/local/share/java/otp.jar
             --build /srv/otp/data --longDistance --transitIndex
    when: osm_download.changed or gtfs_download.changed
    register: build_graph

  - name: Distribute graph
    command: rsync -rl -i --delete
             /srv/otp/data/Graph.obj
             {{ hostvars[item].inventory_hostname }}:/srv/otp/graphs/Graph.obj
    with_items: ${groups.opentripplanner}
    register: distribute_res
    when: build_graph.changed
    changed_when: distribute_res.stdout != ""


- hosts: opentripplanner
  user: root

  tasks:

  - name: Restart OTP
    service:
      name: otp
      state: restarted
    when: distribute_res.changed
