---
- hosts: graphbuilder
  user: root

  tasks:

  - name: Create local Java directory
    file: path=/usr/local/share/java state=directory

  - name: Install OpenTripPlanner
    copy: src=otp-core/target/otp.jar dest=/usr/local/share/java/otp.jar mode=0644


- hosts: opentripplanner
  user: root

  tasks:

  - name: Create local Java directory
    file: path=/usr/local/share/java state=directory mode=0755

  - name: Install OpenTripPlanner
    copy: src=otp-core/target/otp.jar dest=/usr/local/share/java/otp.jar mode=0644
    notify:
    - Restart OTP

  - name: Get OTP graph
    delegate_to: "{{ groups.graphbuilder.0 }}"
    command: rsync -rl -i --delete
             /srv/otp/data/Graph.obj
             {{ inventory_hostname }}:/srv/otp/graphs/Graph.obj
    register: distribute_res
    changed_when: distribute_res.stdout != ""
    notify:
    - Restart OTP

  handlers:

  - name: Restart OTP
    service: name=otp state=restarted
